Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [34]:
N = int(input())
np.arange(N-1, -1, -1)

6


array([5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [33]:
N = int(input())
n_array = np.diag(np.arange(N, -1, -1), k=0)
print(n_array)
print(np.trace(n_array))

5
[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
15


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [5]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [7]:
np.allclose(np.dot(a, linalg.solve(a,b)), b)

True

Задание 4 Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем: На сайт заходит очередной посетитель, о покупках которого известно следующее: Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [36]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [37]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [45]:
def cosine(a, b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    return np.dot( a, b ) / ( aLength * bLength )

In [65]:
cos_list = []
for i in users_stats:
    i_array = np.array(i)
    i_dot = np.dot(next_user_stats, i_array)
    cos = cosine(next_user_stats, i_array)
    cos_list.append(cos)
cos_max = max(cos_list,key=lambda x:float(x))
print(round(cos_max, 4), cos_list.index(cos_max)+1)

0.9487 8
